const cartMenuContainer = document.querySelector("#cart_menu_container");
const cartNavIcon = document.querySelector("#cart_nav_icon");
const closeButton = document.querySelector("#closeButton");
const mostPopularContainer = document.querySelector('#mostPopularContainer');

const productsArray = [
	{
		id: 1,
		name: "Muzzarela",
		category: "pizza",
		img: "./assets/img/pizzas/pizza3.png",
		popular:true,
		price: 1250,
	},
	{
		id: 2,
		name: "Con peperoni",
		category: "pizza",
		img: "./assets/img/pizzas/pizza6.png",
		popular:false,
		price: 1400,
	},
	{
		id: 3,
		name: "Con jamon crudo y rucula",
		category: "pizza",
		img: "./assets/img/pizzas/pizza2.png",
		popular:true,
		price: 1250,
	},
	{
		id: 4,
		name: "Con vegetales",
		category: "pizza",
		img: "./assets/img/pizzas/pizza1.png",
		popular:false,
		price: 1100,
	},
	{
		id: 5,
		name: "Con Cheddar y hongos",
		category: "pizza",
		img: "./assets/img/pizzas/pizza4.png",
		popular:true,
		price: 1430,
	},
	{
		id: 6,
		name: "Pizza veggie",
		category: "pizza",
		img: "./assets/img/pizzas/pizza8.png",
		popular:false,
		price: 1290,
	},
	{
		id: 7,
		name: "Hamburguesa completa",
		category: "hamburguesa",
		img: "./assets/img/products/completa.jgp",
		popular:true,
		price: 800,
	},
	{
		id: 8,
		name: "Con queso",
		category: "hamburguesa",
		img: "./assets/img/products/simpleQueso.webp",
		popular:true,
		price: 750,
	},
	{
		id: 9,
		name: "Con queso Brie y hongos",
		category: "hamburguesa",
		img: "./assets/img/products/mushroomBrie.jgp",
		popular:false,
		price: 750,
	},
	{
		id: 10,
		name: "Con barbacoa",
		category: "hamburguesa",
		img: "./assets/img/products/barbecue.webp",
		popular:true,
		price: 850,
	},
	{
		id: 11,
		name: "Con aros de cebolla",
		category: "hamburguesa",
		img: "./assets/img/products/onionRing.jgp",
		popular:false,
		price: 850,
	},
	{
		id: 12,
		name: "Veggie de lentejas",
		category: "hamburguesa",
		img: "./assets/img/products/veggie.jgp",
		popular:false,
		price: 700,
	},
	{
		id: 13,
		name: "Papas fritas",
		category: "papas",
		img: "./assets/img/products/fries.jgp",
		popular:true,
		price: 700,
	},
	{
		id: 14,
		name: "Con Bacon&Cheddar",
		category: "papas",
		img: "./assets/img/products/friesBacon.jgp",
		popular:false,
		price: 800,
	},
	{
		id: 15,
		name: "Con Chili",
		category: "papas",
		img: "./assets/img/products/friesChili.jgp",
		popular:false,
		price: 750,
	},
	{
		id: 16,
		name: "Con queso crema y ciboulette",
		category: "papas",
		img: "./assets/img/products/friesCreamChesse.jgp",
		popular:true,
		price: 1000,
	},
	{
		id: 17,
		name: "Con carne",
		category: "wrap",
		img: "./assets/img/products/wrapMeat.jpg",
		popular:false,
		price: 1000,
	},
	{
		id: 18,
		name: "Con atun",
		category: "wrap",
		img: "./assets/img/products/wrapAtun.jpg",
		popular:false,
		price: 900,
	},
	{
		id: 19,
		name: "De vegetales",
		category: "wrap",
		img: "./assets/img/products/wrapVeggie.webp",
		popular:false,
		price: 950,
	},
	{
		id: 20,
		name: "Tacos de carne",
		category: "mexicana",
		img: "./assets/img/products/tacosMeat.webp",
		popular:true,
		price: 1250,
	},
	{
		id: 21,
		name: "Tacos Veggie",
		category: "mexicana",
		img: "./assets/img/products/tacosVeggie.jgp",
		popular:true,
		price: 1000,
	},
	{
		id: 22,
		name: "Quesadilla",
		category: "mexicana",
		img: "./assets/img/products/quesadilla.jpg",
		popular:false,
		price: 600,
	},
	{
		id: 23,
		name: "Nachos con cheddar",
		category: "mexicana",
		img: "./assets/img/products/nachosCheddar.webp",
		popular:false,
		price: 780,
	},
	{
		id: 24,
		name: "Nachos full",
		category: "mexicana",
		img: "./assets/img/products/nachosBeans.jpg",
		popular:false,
		price: 950,
	},
	{
		id: 25,
		name: "De frutilla",
		category: "batido",
		img: "./assets/img/products/shakeStrawberry.webp",
		popular:false,
		price: 600,
	},
	{
		id: 26,
		name: "De chocolate",
		category: "batido",
		img: "./assets/img/products/shakeChocolate.jgp",
		popular:true,
		price: 600,
	},
	{
		id: 27,
		name: "Sprinkle",
		category: "batido",
		img: "./assets/img/products/shakeSprinkle.webp",
		popular:false,
		price: 600,
	},
	{
		id: 28,
		name: "De Mashmellow",
		category: "batido",
		img: "./assets/img/products/shakeMashmellow.jgp",
		popular:true,
		price: 600,
	},
];
